FROM oven/bun:1.3.10-slim AS builder
WORKDIR /app

COPY package.json turbo.json bun.lockb ./
COPY apps/worker ./apps/worker
COPY packages ./packages

RUN bun install --frozen-lockfile
RUN bun build apps/worker/src/index.ts --target=bun --outfile=dist/worker.js

FROM oven/bun:1.3.10-slim
WORKDIR /app
COPY --from=builder /app/dist/worker.js ./worker.js
EXPOSE 3020
CMD ["bun", "run", "worker.js"]
