FROM oven/bun:1.3.10-slim AS builder
WORKDIR /app

COPY package.json turbo.json bun.lockb ./
COPY apps/web ./apps/web
COPY packages ./packages

# Install dependencies and build
RUN bun install
RUN bun run --filter=@harga/web build

FROM nginx:alpine
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
