FROM oven/bun:1.3.10-slim AS builder
WORKDIR /app

COPY package.json turbo.json bun.lockb ./
COPY apps/scheduler ./apps/scheduler
COPY packages ./packages

RUN bun install --frozen-lockfile
RUN bun build apps/scheduler/src/index.ts --target=bun --outfile=dist/scheduler.js

FROM oven/bun:1.3.10-slim
WORKDIR /app
COPY --from=builder /app/dist/scheduler.js ./scheduler.js
EXPOSE 3010
CMD ["bun", "run", "scheduler.js"]
